- name: "fetch images for centos{{ os_version }}"
  get_url:
    dest: "/home/stack/overcloud_imgs/{{item.file}}"
    mode: 0644
    url: "https://images.rdoproject.org/centos{{ os_version }}/{{tripleo_version}}/rdo_trunk/current-tripleo/{{item.file}}"
  retries: 10
  delay: 5
  loop: "{{ overcloud_images }}"
  loop_control:
    label: "{{item.file}}"

- name: uncompress images
  unarchive:
    creates: "/home/stack/overcloud_imgs/{{item.content}}"
    dest: "/home/stack/overcloud_imgs/"
    remote_src: true
    src: "/home/stack/overcloud_imgs/{{item.file}}"
  loop: "{{ overcloud_images }}"
  loop_control:
    label: "{{item.file}}"
